#pragma once

#define VER_PRODUCTBUILD 560
#define VER_PRODUCTVERSION_STR_W L"2eef37d-dev"
#define VER_FILEVERSION_STR_W VER_PRODUCTVERSION_STR_W
#define VER_BRANCHVERSION_STR_W L"haxi0/MinecraftConsoles/main"
#define VER_NETWORK VER_PRODUCTBUILD
